"use client";
/* eslint-disable react/prop-types */
import { useState, useEffect, useCallback, useRef } from "react";
import ReactMarkdown from "react-markdown";
import { FiUpload, FiFile, FiX, FiCheck, FiAlertCircle, FiDownload } from "react-icons/fi";
import { AiOutlineFilePdf } from "react-icons/ai";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { motion, AnimatePresence } from 'framer-motion';

const API_BASE_URL = "http://localhost:8000";

// Add generatePDF function
const generatePDF = async (result, patientInfo) => {
  try {
    const pdfDoc = await PDFDocument.create();
    let page = pdfDoc.addPage([595.276, 841.890]); // A4 size
    const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Helper function to draw wrapped text
    const drawWrappedText = (text, x, y, maxWidth, fontSize, font, color = rgb(0, 0, 0)) => {
      const words = text.split(/\s+/);
      let line = '';
      let currentY = y;
      const lineHeight = fontSize * 1.2;

      for (const word of words) {
        const testLine = line + (line ? ' ' : '') + word;
        const width = font.widthOfTextAtSize(testLine, fontSize);

        if (width > maxWidth && line !== '') {
          page.drawText(line, {
            x,
            y: currentY,
            size: fontSize,
            font,
            color,
          });
          line = word;
          currentY -= lineHeight;

          // Add new page if needed
          if (currentY < 50) {
            const newPage = pdfDoc.addPage([595.276, 841.890]);
            page = newPage;
            currentY = page.getHeight() - 50;
          }
        } else {
          line = testLine;
        }
      }

      // Draw remaining text
      if (line) {
        page.drawText(line, {
          x,
          y: currentY,
          size: fontSize,
          font,
          color,
        });
        currentY -= lineHeight;
      }

      return currentY;
    };

    // Add logo
    try {
      const logoResponse = await fetch('/images/logo.png');
      const logoImageBytes = await logoResponse.arrayBuffer();
      const logoImage = await pdfDoc.embedPng(logoImageBytes);
      const logoDims = logoImage.scale(0.5);
      page.drawImage(logoImage, {
        x: 50,
        y: page.getHeight() - 100,
        width: logoDims.width,
        height: logoDims.height,
      });
    } catch (error) {
      console.error('Error loading logo:', error);
    }

    // Header
    page.drawText('ZoctorAI Medical Report', {
      x: 50,
      y: page.getHeight() - 150,
      size: 24,
      font: helveticaBold,
      color: rgb(0, 0.5, 1), // Prime color
    });

    // Date
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    page.drawText(`Report Date: ${currentDate}`, {
      x: 50,
      y: page.getHeight() - 180,
      size: 12,
      font: helveticaFont,
    });

    // Patient Information Section
    let currentY = page.getHeight() - 230;
    page.drawText('Patient Information', {
      x: 50,
      y: currentY,
      size: 16,
      font: helveticaBold,
      color: rgb(0, 0.5, 1),
    });

    currentY -= 30;

    // Draw patient info if available
    if (patientInfo) {
      const infoLines = [
        `Name: ${patientInfo.firstName} ${patientInfo.lastName}`,
        `Date of Birth: ${new Date(patientInfo.dateOfBirth).toLocaleDateString()}`,
        `Gender: ${patientInfo.gender}`,
        `Blood Type: ${patientInfo.bloodType}`,
      ];

      for (const line of infoLines) {
        page.drawText(line, {
          x: 50,
          y: currentY,
          size: 12,
          font: helveticaFont,
        });
        currentY -= 20;
      }
    }

    currentY -= 30;

    // Summary Section
    page.drawText('Medical Report Summary', {
      x: 50,
      y: currentY,
      size: 16,
      font: helveticaBold,
      color: rgb(0, 0.5, 1),
    });

    currentY -= 30;

    // Draw the summary text with proper word wrapping
    const maxWidth = 495; // page width minus margins
    currentY = drawWrappedText(
      result.summary,
      50,
      currentY,
      maxWidth,
      12,
      helveticaFont
    );

    // Footer
    page.drawText('Generated by ZoctorAI - AI-Powered Medical Report Analysis', {
      x: 50,
      y: 30,
      size: 10,
      font: helveticaFont,
      color: rgb(0.5, 0.5, 0.5),
    });

    // Generate PDF bytes
    const pdfBytes = await pdfDoc.save();
    return pdfBytes;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

const FileUpload = ({ userId }) => {
  const navigate = useNavigate();
  const [selectedFiles, setSelectedFiles] = useState([]);
  const [analysisResults, setAnalysisResults] = useState([]);
  const [userQuestion, setUserQuestion] = useState("");
  const [chatHistory, setChatHistory] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [dragActive, setDragActive] = useState(false);
  const [fileProgress, setFileProgress] = useState({});
  const [fileStatuses, setFileStatuses] = useState({});
  const [patientInfo, setPatientInfo] = useState(null);
  const [isTyping, setIsTyping] = useState(false);
  
  const chatContainerRef = useRef(null);

  useEffect(() => {
    const token = localStorage.getItem("accessToken");
    if (!token) {
      navigate("/login");
      return;
    }
    if (!userId) {
      navigate("/dashboard");
      return;
    }
  }, [userId, navigate]);

  useEffect(() => {
    const fetchPatientInfo = async () => {
      try {
        const token = localStorage.getItem("accessToken");
        if (!token) return;

        const response = await axios.get(`${API_BASE_URL}/api/auth/me`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        setPatientInfo(response.data);
      } catch (error) {
        console.error('Error fetching patient info:', error);
      }
    };

    if (userId) {
      fetchPatientInfo();
    }
  }, [userId]);

  useEffect(() => {
    const loadChatHistory = () => {
      try {
        const savedHistory = localStorage.getItem(`chat_history_${userId}`);
        if (savedHistory) {
          setChatHistory(JSON.parse(savedHistory));
        }
      } catch (error) {
        console.error('Error loading chat history:', error);
      }
    };

    if (userId) {
      loadChatHistory();
    }
  }, [userId]);

  useEffect(() => {
    if (userId && chatHistory.length > 0) {
      localStorage.setItem(`chat_history_${userId}`, JSON.stringify(chatHistory));
    }
  }, [chatHistory, userId]);

  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [chatHistory]);

  const handleDrag = useCallback((e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    const files = Array.from(e.dataTransfer.files);
    handleFiles(files);
  }, []);

  const handleFiles = (files) => {
    const pdfFiles = files.filter(file => file.type === 'application/pdf');
    const newFiles = pdfFiles.map(file => ({
      file,
      id: Math.random().toString(36).substr(2, 9),
      previewUrl: URL.createObjectURL(file),
      status: 'pending' // pending, uploading, success, error
    }));

    if (files.length !== pdfFiles.length) {
      setErrorMessage("Only PDF files are allowed");
    }

    setSelectedFiles(prev => [...prev, ...newFiles]);
    setFileStatuses(prev => ({
      ...prev,
      ...Object.fromEntries(newFiles.map(f => [f.id, 'pending']))
    }));
    setFileProgress(prev => ({
      ...prev,
      ...Object.fromEntries(newFiles.map(f => [f.id, 0]))
    }));
  };

  const handleRemoveFile = (fileId) => {
    setSelectedFiles(prev => {
      const updatedFiles = prev.filter(f => f.id !== fileId);
      // Cleanup preview URL
      const removedFile = prev.find(f => f.id === fileId);
      if (removedFile?.previewUrl) {
        URL.revokeObjectURL(removedFile.previewUrl);
      }
      return updatedFiles;
    });
  };

  // Add function to clear chat history
  const clearChatHistory = useCallback(() => {
    setChatHistory([]);
    localStorage.removeItem(`chat_history_${userId}`);
  }, [userId]);

  // Clear chat history when component unmounts
  useEffect(() => {
    return () => {
      clearChatHistory();
    };
  }, [clearChatHistory]);

  const handleSubmit = async (event) => {
    event.preventDefault();
    
    try {
      if (selectedFiles.length === 0) {
        setErrorMessage("Please select at least one file");
        return;
      }

      // Clear existing chat history when analyzing new files
      clearChatHistory();

      // Validate all files
      for (const fileObj of selectedFiles) {
        if (!fileObj.file.type || fileObj.file.type !== 'application/pdf') {
          setErrorMessage(`${fileObj.file.name} is not a PDF file`);
          return;
        }

        const MAX_FILE_SIZE = 10 * 1024 * 1024;
        if (fileObj.file.size > MAX_FILE_SIZE) {
          setErrorMessage(`${fileObj.file.name} exceeds 10MB limit`);
          return;
        }
      }

      const token = localStorage.getItem("accessToken");
      if (!token || !userId) {
        setErrorMessage("Authentication required");
        navigate("/login");
        return;
      }

      setIsLoading(true);
      setErrorMessage("");

      const formData = new FormData();
      selectedFiles.forEach(fileObj => {
        formData.append("files", fileObj.file);
      });

      const response = await axios.post(
        `${API_BASE_URL}/api/upload`,
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
            "Authorization": `Bearer ${token}`,
          },
          onUploadProgress: (progressEvent) => {
            const progress = Math.round(
              (progressEvent.loaded * 100) / (progressEvent.total || 0)
            );
            setFileProgress(prev => ({
              ...prev,
              total: progress
            }));
          },
          withCredentials: true,
        }
      );

      console.log("Upload Response:", response.data);

      if (response.data && response.data.success) {
        // Set analysis results with the summary
        setAnalysisResults([{
          _id: `analysis_${Date.now()}`,
          files: response.data.file_info,
          summary: response.data.summary,
          timestamp: response.data.timestamp
        }]);

        setSuccessMessage(`Successfully processed ${response.data.files_processed} file(s)`);
        setSelectedFiles([]);
        setFileStatuses({});
        setFileProgress({});
      } else {
        throw new Error("Invalid response format from server");
      }

    } catch (error) {
      console.error("Upload error details:", {
        message: error.message,
        status: error.response?.status,
        data: error.response?.data,
      });

      // 7. Specific Error Handling
      const errorHandler = {
        400: "Invalid file format or request",
        401: () => {
          setErrorMessage("Session expired. Please log in again.");
          navigate("/login");
        },
        403: () => {
          setErrorMessage("Access denied. Please check your permissions.");
          navigate("/login");
        },
        413: "File size too large. Maximum size is 10MB.",
        500: "Server error. Please try again later.",
        ECONNABORTED: "Request timed out. Please try again.",
      };

      const errorMessage = typeof errorHandler[error.response?.status] === 'function'
        ? errorHandler[error.response?.status]()
        : errorHandler[error.response?.status] || errorHandler[error.code] ||
          "Error uploading file. Please try again.";

      setErrorMessage(errorMessage);

    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    return () => {
      selectedFiles.forEach(fileObj => {
        if (fileObj.previewUrl) {
          URL.revokeObjectURL(fileObj.previewUrl);
        }
      });
    };
  }, []);

  const handleAskQuestion = async () => {
    if (!userQuestion || !analysisResults.length) {
      setErrorMessage("Please analyze at least one report before asking a question.");
      return;
    }
    try {
      setIsLoading(true);
      setErrorMessage("");
      
      const newUserMessage = {
        type: 'user',
        content: userQuestion,
        timestamp: new Date().toISOString()
      };
      setChatHistory(prev => [...prev, newUserMessage]);
      setUserQuestion("");
      
      const token = localStorage.getItem("accessToken");
      if (!token) {
        throw new Error("User is not authenticated. Please log in again.");
      }

      // Show typing indicator
      setIsTyping(true);

      const response = await fetch(`${API_BASE_URL}/api/chat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`,
        },
        body: JSON.stringify({
          message: userQuestion,
          context: analysisResults.map(result => result.summary).join("\n"),
        }),
      });

      if (!response.ok) {
        throw new Error(`Error: ${response.status} - ${response.statusText}`);
      }
      const result = await response.json();
      
      // Hide typing indicator
      setIsTyping(false);

      if (result.response) {
        const newAIMessage = {
          type: 'ai',
          content: result.response,
          timestamp: new Date().toISOString()
        };
        setChatHistory(prev => [...prev, newAIMessage]);
      } else {
        throw new Error("No answer returned from the server.");
      }
    } catch (error) {
      console.error("Error asking question:", error);
      setIsTyping(false);
      setErrorMessage(error.message || "Failed to get an answer to your question.");
      
      const errorMessage = {
        type: 'error',
        content: error.message || "Failed to get an answer to your question.",
        timestamp: new Date().toISOString()
      };
      setChatHistory(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const formatFileSize = (size) => {
    const units = ["B", "KB", "MB", "GB"];
    let index = 0;
    while (size >= 1024 && index < units.length - 1) {
      size /= 1024;
      index++;
    }
    return `${size.toFixed(2)} ${units[index]}`;
  };

  const FileStatusIndicator = ({ status, progress }) => {
    const statusConfig = {
      pending: { color: 'text-gray-400', icon: FiFile },
      uploading: { color: 'text-blue-500', icon: FiUpload },
      success: { color: 'text-green-500', icon: FiCheck },
      error: { color: 'text-red-500', icon: FiAlertCircle }
    };

    const StatusIcon = statusConfig[status].icon;

    return (
      <div className="flex items-center">
        <StatusIcon className={`w-5 h-5 ${statusConfig[status].color}`} />
        {status === 'uploading' && progress !== undefined && (
          <span className="ml-2 text-sm text-gray-600">{progress}%</span>
        )}
      </div>
    );
  };

  const handleDownloadSummary = async (result) => {
    try {
      const pdfBytes = await generatePDF(result, patientInfo);
      
      // Create blob and download
      const blob = new Blob([pdfBytes], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `ZoctorAI_Medical_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading summary:', error);
      setErrorMessage('Failed to generate PDF report. Please try again.');
    }
  };

  // Animation variants
  const messageVariants = {
    hidden: { opacity: 0, y: 20, scale: 0.9 },
    visible: { 
      opacity: 1, 
      y: 0, 
      scale: 1,
      transition: { 
        type: "spring",
        stiffness: 200,
        damping: 20
      }
    },
    exit: { 
      opacity: 0,
      scale: 0.9,
      transition: { duration: 0.2 }
    }
  };

  // Typing indicator component
  const TypingIndicator = () => (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 10 }}
      className="flex items-start space-x-2"
    >
      <div className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center flex-shrink-0">
        <svg className="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
        </svg>
      </div>
      <div className="bg-white border border-gray-200 px-4 py-2 rounded-[20px] rounded-tl-[5px]">
        <div className="flex space-x-1">
          <motion.div
            className="w-2 h-2 bg-gray-400 rounded-full"
            animate={{ y: [0, -5, 0] }}
            transition={{ duration: 0.5, repeat: Infinity, delay: 0 }}
          />
          <motion.div
            className="w-2 h-2 bg-gray-400 rounded-full"
            animate={{ y: [0, -5, 0] }}
            transition={{ duration: 0.5, repeat: Infinity, delay: 0.2 }}
          />
          <motion.div
            className="w-2 h-2 bg-gray-400 rounded-full"
            animate={{ y: [0, -5, 0] }}
            transition={{ duration: 0.5, repeat: Infinity, delay: 0.4 }}
          />
        </div>
      </div>
    </motion.div>
  );

  return (
    <div className="flex flex-col min-h-screen bg-gray-50 p-4">
      <div className="max-w-6xl mx-auto w-full space-y-8">
        {/* Section 1: File Upload */}
        <div className="bg-white rounded-xl shadow-lg p-6">
          <div className="flex items-center space-x-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-prime flex items-center justify-center">
              <FiUpload className="w-6 h-6 text-white" />
            </div>
            <h2 className="text-2xl font-bold text-gray-800">Upload Your Medical Reports</h2>
          </div>
          
          <div
            onDragEnter={handleDrag}
            onDragLeave={handleDrag}
            onDragOver={handleDrag}
            onDrop={handleDrop}
            className={`border-2 border-dashed rounded-xl p-8 transition-all duration-200 ${
              dragActive
                ? "border-blue-500 bg-blue-50"
                : "border-gray-300 hover:border-prime"
            }`}
          >
            <input
              type="file"
              id="file-upload"
              multiple
              accept=".pdf"
              onChange={(e) => handleFiles(Array.from(e.target.files))}
              className="hidden"
            />
            <label
              htmlFor="file-upload"
              className="cursor-pointer flex flex-col items-center"
            >
              <FiUpload className={`w-12 h-12 mb-4 ${
                dragActive ? "text-blue-500" : "text-gray-400"
              }`} />
              <span className="text-gray-600 font-medium text-center">
                {dragActive
                  ? "Drop your files here"
                  : "Drag and drop your PDF files here, or click to browse"}
              </span>
              <span className="text-sm text-gray-500 mt-2">
                Maximum 10 files, 10MB each
              </span>
            </label>
          </div>

          {selectedFiles.length > 0 && (
            <div className="mt-6 space-y-3">
              {selectedFiles.map(fileObj => (
                <div
                  key={fileObj.id}
                  className="bg-gray-50 rounded-lg p-4 flex items-center justify-between"
                >
                  <div className="flex items-center space-x-4 flex-1">
                    <AiOutlineFilePdf className="w-8 h-8 text-red-500" />
                    <div className="flex-1">
                      <p className="font-medium text-gray-800 truncate">
                        {fileObj.file.name}
                      </p>
                      <p className="text-sm text-gray-500">
                        {formatFileSize(fileObj.file.size)}
                      </p>
                    </div>
                    <FileStatusIndicator
                      status={fileStatuses[fileObj.id]}
                      progress={fileProgress[fileObj.id]}
                    />
                  </div>
                  {fileStatuses[fileObj.id] !== 'uploading' && (
                    <button
                      onClick={() => handleRemoveFile(fileObj.id)}
                      className="ml-4 text-gray-400 hover:text-red-500 transition-colors"
                    >
                      <FiX className="w-5 h-5" />
                    </button>
                  )}
                </div>
              ))}
            </div>
          )}

          <button
            onClick={handleSubmit}
            disabled={isLoading || selectedFiles.length === 0}
            className={`mt-6 w-full py-3 px-4 rounded-lg text-white font-medium transition-all duration-200 ${
              isLoading || selectedFiles.length === 0
                ? "bg-gray-400 cursor-not-allowed"
                : "bg-prime hover:bg-blue-600 shadow-lg hover:shadow-xl"
            }`}
          >
            {isLoading ? (
              <span className="flex items-center justify-center">
                <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Processing Files...
              </span>
            ) : (
              `Upload and Analyze ${selectedFiles.length} ${selectedFiles.length === 1 ? 'File' : 'Files'}`
            )}
          </button>
        </div>

        {/* Section 2: Generated Summary */}
        {analysisResults.length > 0 && (
          <div className="bg-white rounded-xl shadow-lg p-6">
            <div className="flex items-center space-x-3 mb-6">
              <div className="w-10 h-10 rounded-full bg-green-500 flex items-center justify-center">
                <FiCheck className="w-6 h-6 text-white" />
              </div>
              <h2 className="text-2xl font-bold text-gray-800">Analysis Summary</h2>
            </div>

            <div className="space-y-6">
              {analysisResults.map((result, index) => (
                <div key={result._id || index} className="bg-gray-50 rounded-xl p-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="text-xl font-semibold text-gray-800">Your Medical Report Analysis</h3>
                    <button
                      onClick={() => handleDownloadSummary(result)}
                      className="flex items-center gap-2 px-4 py-2 bg-prime text-white rounded-lg hover:bg-blue-600 transition-colors"
                    >
                      <FiDownload className="w-5 h-5" />
                      Download Report
                    </button>
                  </div>

                  <div className="prose prose-sm max-w-none bg-white p-6 rounded-lg border border-gray-200">
                    <ReactMarkdown className="text-gray-700">
                      {result.summary}
                    </ReactMarkdown>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Section 3: AI Chat */}
        {analysisResults.length > 0 && (
          <div className="bg-white rounded-xl shadow-lg p-6">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center">
                <svg className="w-8 h-8 text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
                <h2 className="text-2xl font-bold text-gray-800 ml-3">Ask Questions About Your Reports</h2>
              </div>
              
              {chatHistory.length > 0 && (
                <motion.button
                  onClick={clearChatHistory}
                  className="px-4 py-2 text-sm text-red-600 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors duration-200 flex items-center space-x-1"
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  <span>Clear Chat</span>
                </motion.button>
              )}
            </div>

            <div className="bg-gray-50 rounded-xl p-6 min-h-[400px] flex flex-col">
              <div 
                ref={chatContainerRef}
                className="flex-grow space-y-6 overflow-y-auto mb-6 max-h-[500px] scroll-smooth"
              >
                <AnimatePresence>
                  {chatHistory.map((message, index) => (
                    <motion.div
                      key={message.timestamp + index}
                      layout
                      initial="hidden"
                      animate="visible"
                      exit="exit"
                      variants={messageVariants}
                      className="space-y-6"
                    >
                      {message.type === 'user' ? (
                        <div className="flex justify-end items-start space-x-2">
                          <motion.div 
                            className="flex flex-col items-end"
                            initial={{ x: 20, opacity: 0 }}
                            animate={{ x: 0, opacity: 1 }}
                            transition={{ type: "spring", stiffness: 200, damping: 20 }}
                          >
                            <div className="bg-[#0B84FE] text-[#fff] px-4 py-2 rounded-[20px] rounded-tr-[5px] max-w-[90%] shadow-sm">
                              <p className="text-[15px] leading-[1.4]">{message.content}</p>
                            </div>
                            <span className="text-xs text-gray-500 mt-1">
                              {new Date(message.timestamp).toLocaleTimeString()}
                            </span>
                          </motion.div>
                          <div className="w-8 h-8 rounded-full bg-[#6f6f6f] flex-shrink-0 flex items-center justify-center">
                            <span className="text-[#fff] font-bold text-sm">ZI</span>
                          </div>
                        </div>
                      ) : message.type === 'ai' ? (
                        <div className="flex items-start space-x-2">
                          <div className="w-8 h-8 rounded-full bg-[#9930da] flex items-center justify-center flex-shrink-0">
                            <svg className="w-5 h-5 text-[#fff]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                            </svg>
                          </div>
                          <motion.div 
                            className="flex flex-col"
                            initial={{ x: -20, opacity: 0 }}
                            animate={{ x: 0, opacity: 1 }}
                            transition={{ type: "spring", stiffness: 200, damping: 20 }}
                          >
                            <div className="bg-[#76ccf0] border  px-4 py-2 rounded-[20px] rounded-tl-[5px] max-w-[80%] shadow-sm">
                              <p className="text-[15px] leading-[1.4] text-gray-800">{message.content}</p>
                            </div>
                            <span className="text-xs text-[#8d8d8d] mt-1">
                              {new Date(message.timestamp).toLocaleTimeString()}
                            </span>
                          </motion.div>
                        </div>
                      ) : (
                        <motion.div 
                          className="flex justify-center"
                          initial={{ y: -10, opacity: 0 }}
                          animate={{ y: 0, opacity: 1 }}
                          exit={{ y: 10, opacity: 0 }}
                        >
                          <div className="bg-red-50 text-red-600 px-4 py-2 rounded-lg text-sm">
                            {message.content}
                          </div>
                        </motion.div>
                      )}
                    </motion.div>
                  ))}
                </AnimatePresence>
                
                {/* Typing Indicator */}
                <AnimatePresence>
                  {isTyping && <TypingIndicator />}
                </AnimatePresence>
              </div>

              {/* Question Input */}
              <motion.div 
                className="flex items-center space-x-3 bg-white rounded-full border border-gray-200 p-1 pl-4"
                initial={{ y: 20, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ type: "spring", stiffness: 200, damping: 20 }}
              >
                <input
                  type="text"
                  placeholder="Type your question here..."
                  value={userQuestion}
                  onChange={(e) => setUserQuestion(e.target.value)}
                  className="flex-1 text-[15px] focus:outline-none bg-transparent"
                  onKeyPress={(e) => {
                    if (e.key === 'Enter' && !isLoading && userQuestion.trim()) {
                      handleAskQuestion();
                    }
                  }}
                />
                <button
                  onClick={handleAskQuestion}
                  disabled={isLoading || !userQuestion.trim()}
                  className={`px-4 py-2 rounded-full transition-all duration-200 ${
                    isLoading || !userQuestion.trim()
                      ? "bg-gray-100 text-gray-400 cursor-not-allowed"
                      : "bg-[#0B84FE] text-white hover:bg-blue-600"
                  }`}
                >
                  {isLoading ? (
                    <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                  ) : (
                    "Ask"
                  )}
                </button>
              </motion.div>
            </div>
          </div>
        )}

        {/* Error Message */}
        {errorMessage && (
          <div className="fixed bottom-4 right-4 bg-red-50 border-l-4 border-red-500 text-red-700 p-4 rounded-lg shadow-lg max-w-md">
            {errorMessage}
          </div>
        )}

        {/* Success Message */}
        {successMessage && (
          <div className="fixed bottom-4 right-4 bg-green-50 border-l-4 border-green-500 text-green-700 p-4 rounded-lg shadow-lg max-w-md">
            {successMessage}
          </div>
        )}
      </div>
    </div>
  );
};

export default FileUpload;