import YourReportPage from "../../../pages-src/YourReportPage";

export const metadata = {
  title: "Your Report",
  description: "Access your personalized health report generated by ZoctorAI.",
};

export default function Page() {
  return <YourReportPage />;
}

